name: Postman Tests

on:
  push:
    branches: [ "master", "main" ]

jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Upgraded to v5 to fix the yellow deprecation warning
      - uses: actions/setup-java@v5
        with:
          java-version: '23'
          distribution: 'temurin'

      - name: Start Spring Boot
        run: |
          sed -i 's/\r$//' mvnw
          chmod +x mvnw
          ./mvnw spring-boot:run "-Dspring-boot.run.profiles=test" &
          
          # Forces GitHub to wait dynamically until port 8081 opens
          echo "Waiting for Spring Boot to start on port 8081..."
          timeout 180 bash -c 'while ! nc -z localhost 8081; do sleep 3; done'
          echo "Server is up! Running tests..."

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman Tests
        run: newman run postman/LostAndFound.postman_collection.json --working-dir postman/